### ISSUE TITLE
When I ran pip install -r pip_requirements.txt to install the dependencies, an error occurred.

### ISSUE THREAD

**Issue by zhenyu818** [donggehan/codellmpersonalize#1]
When I entered `pip install -r pip_requirements.txt `to install the dependencies, an error was reported: 
`ERROR: git+git@github.com:yashkant/habitat-lab-fork.git@a8dd6a1e4ce7be7a4d46a3ce679dd997b8000de9#egg=habitat&subdirectory=../../habitat-lab is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file). `
Is this because the following line in pip_requirements.txt is incorrect: 
`git+git@github.com:yashkant/habitat-lab-fork.git@a8dd6a1e4ce7be7a4d46a3ce679dd997b8000de9#egg=habitat&subdirectory=../../habitat-lab`?

**Comment by gdg94** [comment]
Hi, thanks for checking out our code. 
For the issue, can you try changing the line in pip_requirements.txt to the following:
`-e git+ssh://git@github.com:yashkant/habitat-lab-fork.git@a8dd6a1e4ce7be7a4d46a3ce679dd997b8000de9#egg=habitat&subdirectory=../../habitat-lab`

(BTW according to the housekeep original repo's installation instructions, it only required `pip install -r requirements.txt` and running `pip install -r pip_requirements.txt` was not needed)

Please let me know if the problem persists or re-open the issue :)
