### ISSUE TITLE
System requirement, docker linker expired

### ISSUE THREAD

**Issue by peppersaltyy** [donggehan/codellmpersonalize#2]
Hi Could you provide the system requirement for running your code? Like what system, version of python ....
Besides, it seems that your docker link has expired. Could you please make a new link to use your docker?

**Comment by gdg94** [comment]
Hi, thanks a lot for your interest and heads-up about the docker link expiration! I've just updated the docker which should now be renewed.
- The base image is nvidia/cudagl:10.1-devel-ubuntu16.04
- python=3.8, cmake=3.14.0
- for our case we run the code on a headless GPU server, the dockerfile contains download and use of NVIDIA-Linux-x86_64-535.104.05 driver

**Comment by peppersaltyy** [comment]
方便的话能加个微信吗？对你这个工作挺感兴趣的，想聊聊一些想法。我的微信是 xijiejiao
